### PR TITLE
Incorrect translation for unaffected stop codon

### LINKED ISSUE #83: Incorrect translation for unaffected stop codon
In hg38 reference genome, `chr3 149520808 C CTTAA` translates to `NM_015472.6:c.1199_1200insTTAA` and `p.*402*ext*9`.

The resulting protein change is `p.=`, as the stop codon at position 401 is unaffected.

UCSC

Repro :bug: 

```clj
(require '[varity.vcf-to-hgvs :as v2h]) 
(v2h/vcf-variant->protein-hgvs {:chr "chr3" :pos 149520808 :ref "C" :alt "CTTAA"} "/path/to/hg38.fa" "/pat/to//ncbiRefSeq_hg38_20210909.txt.gz") ;=> (#clj-hgvs/hgvs "p.*402*ext*9")
```

### PR DESCRIPTION
**Pull request by nokara26**
Resolve #83 

I added conditional branch that ter-site position is not changed to extension.

### CODE REVIEW

File: src/varity/vcf_to_hgvs/protein.clj [hunk 1]
```diff
@@ -426,26 +431,28 @@
...
-                                                    (last ins)
-                                                    (or (last ins) (first rest-seq))))
-                           (if (= ppos 1) :upstream :downstream)
-                           (if ter-site
-                             (coord/protein-coordinate ter-site)
-                             (coord/unknown-coordinate)))))
+  [ppos pref palt {:keys [ref-prot-seq alt-prot-seq alt-tx-prot-seq c-ter-adjusted-alt-prot-seq ini-offset]}]
+  (if (and (not= ppos 1)
+           (ter-site-same-pos? ref-prot-seq c-ter-adjusted-alt-prot-seq))
+    (mut/protein-no-effect)
```
Comment (nokara26) [inline src/varity/vcf_to_hgvs/protein.clj:437]: In this function, I added line 435-437 and moved seq-info destructuring to args .
And I just fixed indent of following lines.

File: src/varity/vcf_to_hgvs/protein.clj [hunk 2]
```diff
@@ -148,6 +148,11 @@
         alt-positions (set (range pos (+ pos (count ref))))]
     (boolean (seq (s/intersection ter-site-positions alt-positions)))))
 
+(defn- ter-site-same-pos?
+  [ref-prot-seq alt-prot-seq]
+  (let [ter-site-pos (count ref-prot-seq)]
+    (= \* (get alt-prot-seq (dec ter-site-pos)))))
```
Comment (federkasten) [inline src/varity/vcf_to_hgvs/protein.clj:154]:
```suggestion
  (let [ter-site-pos (dec (count ref-prot-seq))]
    (= \* (get alt-prot-seq ter-site-pos))))
```

**Review by federkasten — APPROVED** [review]
