### PR TITLE
Fix frameshift conversion failure

### LINKED ISSUE #58: `vcf-variants->hgvs` omits trailing `fs*`
## Problem
Mutalizer's protein alteration HGVS and varity's one are not identical when a frame-shift alteration leads to both protein substitution and termination.
[Mutalizer says](https://v3.mutalyzer.nl/namechecker/NM_000038.6:c.4244_4250del) `NM_000038.6:c.4244_4250del` is `p.(Ser1415Ilefs*2)` but varity returns `p.S1415I`.

## Repro

I tried to convert `"NM_000038.6:c.4244_4250delGTGGCAT"` to VCF variants with hg19's fasta file and `ncbiRefSeq.txt.gz` downloaded from [here](https://hgdownload.cse.ucsc.edu/goldenpath/hg19/database).
I got protein substitution HGVS like below.

```clojure
(require '[varity.ref-gene :as rg]
         '[varity.vcf-to-hgvs :as v2h]
         '[cljam.io.sequence :as io-seq])

(def ncbi-refseq-hg19 (rg/index (rg/load-ref-seqs "path/to/ncbiRefSeq.txt.gz")))

(with-open [r (io-seq/reader genome-fasta-f)]
  (doall
   (v2h/vcf-variant->hgvs {:chr "chr5", :pos 112175534, :ref "AGTGGCAT", :alt "A"}
                          r ncbi-refseq-hg19)))

({:coding-dna #clj-hgvs/hgvs "NM_001127511.3:c.4190_4196delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1397I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354902.2:c.3971_3977delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1324I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354897.2:c.4274_4280delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1425I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354895.2:c.4244_4250delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1415I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354905.2:c.3764_3770delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1255I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354901.2:c.4067_4073delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1356I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354900.2:c.4121_4127delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1374I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354899.2:c.4160_4166delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1387I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354903.2:c.3941_3947delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1314I"}
 {:coding-dna #clj-hgvs/hgvs "NM_000038.6:c.4244_4250delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1415I"} 
 {:coding-dna #clj-hgvs/hgvs "NM_001354896.2:c.4298_4304delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1433I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354906.2:c.3395_3401delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1132I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354904.2:c.3866_3872delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1289I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001354898.2:c.4169_4175delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1390I"}
 {:coding-dna #clj-hgvs/hgvs "NM_001127510.3:c.4244_4250delGTGGCAT",
  :protein #clj-hgvs/hgvs "p.S1415I"})
```

## Question
1. Is there any deficit in my code, understandings and/or data I used?
2. Is this a intended behavior? If so, is there any way to get HGVS `S1415Ifs*2` in this situation?

### PR DESCRIPTION
**Pull request by totakke**
fixes #58

```clojure
(require '[varity.vcf-to-hgvs :as v2h])

(v2h/vcf-variant->hgvs {:chr "chr5", :pos 112175534, :ref "AGTGGCAT", :alt "A"}
                        "path/to/hg19.fa" "path/to/refGene.txt.gz")
;;=> ({:coding-dna #clj-hgvs/hgvs "NM_001127511:c.4190_4196delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1397Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001127510:c.4244_4250delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1415Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354897:c.4274_4280delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1425Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354896:c.4298_4304delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1433Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354906:c.3395_3401delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1132Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354895:c.4244_4250delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1415Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354905:c.3764_3770delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1255Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354903:c.3941_3947delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1314Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354902:c.3971_3977delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1324Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354901:c.4067_4073delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1356Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354900:c.4121_4127delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1374Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354904:c.3866_3872delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1289Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354899:c.4160_4166delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1387Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_001354898:c.4169_4175delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1390Ifs*2"}
;;    {:coding-dna #clj-hgvs/hgvs "NM_000038:c.4244_4250delGTGGCAT",
;;     :protein #clj-hgvs/hgvs "p.S1415Ifs*2"})
```

I confirmed `lein test :all` passed.

### CODE REVIEW

File: src/varity/vcf_to_hgvs/protein.clj [hunk 1]
```diff
@@ -175,10 +175,12 @@
...
-              (not= ref-prot-rest alt-prot-rest) (if (or (and (empty? palt-only)
-                                                              (= (first alt-prot-rest) \*))
-                                                         (= (last palt-only) \*)) :fs-ter-substitution
-                                                     :frame-shift)
+              (not= ref-prot-rest alt-prot-rest) (if (or (and (= (first alt-prot-rest) \*)
+                                                              (>= nprefo npalto)
+                                                              (= palt (subs pref 0 (count palt))))
+                                                         (= (last palt-only) \*))
+                                                   :fs-ter-substitution
+                                                   :frame-shift)
```
Comment (totakke) [inline src/varity/vcf_to_hgvs/protein.clj:183]: The `fs-ter-subsitution` detection added by #15 is insufficient because `varity.vcf-to-hgvs.common/diff-bases` returns right-side commons as well as left-side commons. In this case,

```clojure
(require '[varity.vcf-to-hgvs.common :refer [diff-bases]])

(diff-bases "SGI" "I")
;;=> ["SG" "" 0 1] ; [pref-only palt-only offset _]
```

So `(empty? palt-only)` cannot detect frameshift in the changed proteins and wrongly detect it as `fs-ter-substitution`. A direct comparison between `pref` and `palt` is needed.

File: test/varity/vcf_to_hgvs_test.clj [hunk 2]
```diff
@@ -205,6 +205,8 @@
         "chr1" 69567 "A" "AT" '("p.L160Sfs*7")
         "chr1" 963222 "GCG" "G" '("p.A386Gfs*12")
         "chr2" 47478341 "T" "TGG" '("p.L762Gfs*2" "p.L696Gfs*2")
+        "chr5" 112839837 "AGTGGCAT" "A" '("p.S1397Ifs*2"
+                                          "p.S1415Ifs*2") ; https://github.com/chrovis/varity/issues/58
```
Comment (totakke) [inline test/varity/vcf_to_hgvs_test.clj:209]: A conversion case of #58 on hg38 assembly.

**Review by federkasten — APPROVED** [review]
LGTM. Thanks for your quick investigation and fix.

File: src/varity/vcf_to_hgvs/protein.clj (hunk 1 above)
Comment (k-kom) [reply src/varity/vcf_to_hgvs/protein.clj:183]: Does that mean `:fs-ter-substitution` had been correct for `(diff-bases "SGI" "S")` but not for `(diff-bases "SGI" "I")`?

**Review by k-kom — APPROVED** [review]
Thank you for the fix and explanation. LGTM

File: src/varity/vcf_to_hgvs/protein.clj (hunk 1 above)
Comment (totakke) [reply src/varity/vcf_to_hgvs/protein.clj:183]: Yes. If the ref proteins `...SGIXXXX...` change into the alt proteins `...S*YYYY...`, that is substitution of `G` and `*`, not frameshift.

In #58 case, the ref proteins `...SGIXXXX...` change into the alt proteins `...I*YYYY...`. That is frameshift caused by the change of `SGI` to `I`.

Comment (k-kom) [reply src/varity/vcf_to_hgvs/protein.clj:183]: Thanks. That makes sense!
