### PR TITLE
Fix 3'-rule errors for certain sequence patterns

### LINKED ISSUE #72: StringIndexOutOfBoundsException in apply-3'-rule
StringIndexOutOfBoundsException occurred following added test case.
#71 

This error seem to happen in apply-3'-rule.

### PR DESCRIPTION
**Pull request by federkasten**
Resolve #72 and #74.

This PR addresses the problem of 3' shifting reported in issue #74 and the out-of-bounds exception reported in issue #72.

I have made some refinements to the `varity.vcf-to-hgvs`. Specifically, I have fixed `varity.vcf-to-hgvs.common/backward-shift` function to work correctly for certain sequence patterns and added error handling to `varity.vcf-to-hgvs.common/apply-3'-rule` for rare cases. 

Additionally, I have fixed the exon boundary handling in `varity.vcf-to-hgvs.protein/read-sequence-info`, which was implemented in #68.

Added test cases is originates from #71 and #73 by @nokara26 Thanks! :heart:

### CODE REVIEW

File: src/varity/vcf_to_hgvs/protein.clj [hunk 1]
```diff
@@ -308,12 +308,14 @@
...
                      (subs (dec (+ ppos offset)))
                      (string/index-of "*"))]
-    (mut/protein-frame-shift (mut/->long-amino-acid ref)
-                             (coord/protein-coordinate (+ ppos offset))
-                             (mut/->long-amino-acid alt)
-                             (if (and ter-site (pos? ter-site))
-                               (coord/protein-coordinate (inc ter-site))
-                               (coord/unknown-coordinate)))))
+    (if (= alt \*)
+      (protein-substitution (+ ppos offset) (str ref) (str alt)) ; eventually fs-ter-substitution
```
Comment (federkasten) [inline src/varity/vcf_to_hgvs/protein.clj:312]: :memo: In certain cases, frameshift would be fixed as `fs-ter-substitution` by [the 3'-rule application to protein sequence](https://github.com/chrovis/varity/blob/e51d56c8384e4050603f7036d8a03bf31878e4fe/src/varity/vcf_to_hgvs/protein.clj#L344). So I have added the `fs-ter-substition` check here.

**Review by nokara26 — APPROVED** [review]
Thank you for the fix! LGTM👍

File: src/varity/vcf_to_hgvs/protein.clj (hunk 1 above)
Comment (totakke) [reply src/varity/vcf_to_hgvs/protein.clj:312]: Indeed, such cases potentially occur as you said. It is extremely rare.

Do you have any case of that? I would like you to add the test case if you already have.

No problem even if you do not have the case. I will approve this PR even then because I think it is a bit difficult to prepare the test case.

**Review by totakke — COMMENTED** [review]
Thank you for fixing the 3'-rule. The implementation looks good to me. I have left only a comment about a test case of `fs-ter-substitution` after 3'-rule.

File: src/varity/vcf_to_hgvs/protein.clj (hunk 1 above)
Comment (federkasten) [reply src/varity/vcf_to_hgvs/protein.clj:312]: Sorry, the variant query I attempted appears no longer comes in this path by the `backward-shift` fix. :thinking: 

Instead, I have added test cases for `varity.vcf-to-hgvs.protein/mutation` in https://github.com/chrovis/varity/pull/75/commits/6b2ef4ce48fdb22573615d8431cf76c2d328017f, which includes inputs before and after the 3'-rule of coding DNA. The 3'-rule for protein sequence and `fs-ter-substitution` check work correctly in both cases.

Comment (totakke) [reply src/varity/vcf_to_hgvs/protein.clj:312]: Okay, thank you very much. The test case using `varity.vcf-to-hgvs.protein/mutation` looks good to me.

**Review by totakke — APPROVED** [review]
