### PR TITLE
Fix alt exon calculation for deletion

### LINKED ISSUE #49: Convert ATM c.2465del correctly
`ATM` (`NM_000051.4`) `c.2465del` should be converted to `p.L822*`, but to `p.L822Cfs*9`. (This is the change from REF `GT` to ALT `G` in `chr11:108129798` in hg19.) In the case of the frameshift, it might not be able to support the possibility that a first amino acid could be a stop codon.

Tested with;

```clj
(v2h/vcf-variant->protein-hgvs {:chr "chr11" :pos 108129798 :ref "GT", :alt "G"} "/path/to/hg19.fa" "/path/to/refGene_hg19.txt.gz") ;=> (#clj-hgvs/hgvs "p.L822Cfs*9")
```

cf. https://mutalyzer.nl/name-checker?description=NM_000051.4%3Ac.2465del

### PR DESCRIPTION
**Pull request by totakke**
I have fixed a bug of `varity.vcf-to-hgvs.protein/alt-exon-ranges` when a variant is deletion on just before the exon end. (#49)

```clj
(v2h/vcf-variant->protein-hgvs {:chr "chr11" :pos 108129798 :ref "GT", :alt "G"}
                               "/path/to/hg19.fa "/path/to/refGene_hg19.txt.gz")
;;=> (#clj-hgvs/hgvs "p.L822*")
```

I confirmed `lein test :all` passed.

fixes #49

### CODE REVIEW

File: test/varity/vcf_to_hgvs_test.clj [hunk 1]
```diff
@@ -182,6 +182,7 @@
         "chr7" 55174771 "AGGAATTAAGAGAAGC" "A" '("p.E746_A750del") ; cf. rs121913421 (+)
         "chr1" 247815239 "AAGG" "A" '("p.S163del") ; cf. rs35979231 (-)
         "chr2" 29223408 "AAGCAGT" "A" '("p.Y1096_C1097del") ; cf. rs776101205 (-)
+        "chr11" 108259071 "GT" "G" '("p.L822*") ; https://github.com/chrovis/varity/issues/49
```
Comment (totakke) [inline test/varity/vcf_to_hgvs_test.clj:185]: I have lifted the variant of #49 over to hg38 and added to the test.

**Review by federkasten — APPROVED** [review]
LGTM 🙆‍♂️ Thanks for the quick fix!
